### PR TITLE
listSources

### PR DESCRIPTION
**Pull request by bobbytables**
The listSources method does 2 calls to mongodb to retrieve collections. Slimmed down to only do one.

### CODE REVIEW

**Comment by AD7six** [comment]
I think you've accidentally pushed a load of different changes into the same branch. the listSources change doesn't appear to be present.

**Comment by bobbytables** [comment]
Looks like you're correct. I'll apply that specific change. Wasn't aware that my other commits would be put into this pull request. I'm attempting to create more functionality to include mongo functionality such $inc (increment).

For now I'll close this request.

**Comment by AD7six** [comment]
ah..

well, the commit this ticket was supposed to be for is fine; regarding operators it's probably in your interest to check what ichi is up to

https://github.com/ichikaway/cakephp-mongodb/commits/updateOperator

specifically https://github.com/ichikaway/cakephp-mongodb/commit/f008e06e2a8c1e4e3c24d0dcd6d8b096634085b2

**Comment by ichikaway** [comment]
I merge updateOperator branch to master and push it now.
https://github.com/ichikaway/cakephp-mongodb/commit/924d52530503f1e5d3056065fd8589d2d8c831b2

You can set any mongodb operators instead of $set.

Now, Upsert isn't supported, because CakePHP handles Insert/Update from saving data.

**Pull request closed without merging**
