### PR TITLE
i have made the amend to the code as suggested by my previous pull request.

### PR DESCRIPTION
**Pull request by jameslarking**
test case and change to datasource class in request

thanks

### CODE REVIEW

**Comment by AD7six** [comment]
why only in the case of find('all') return an array? that doesn't seem to match how all other datasources work in cake. This change also makes it impossible to know if there was a db error - because whereas now, you get null if there was an error or no result, with this change you get an empty array whether there was a db error or not.

The test is a nice start though - should be able to flesh that out easily to cover all permutations

**Comment by jameslarking** [comment]
my understanding is that in other datasources if i do a find('all') in mysql and there are no records found I get an empty array back.  if i do a find('one') then i get a null value and if i do a find('count') then i get an int zero.  Currently if you use standard baked templates for an index page with an empty recordset you will get an error on the attempted foreach that is does.  I'm not specifically saying that it is wrong just that it is different than mysql or postgres (the only two that I have used).

**Comment by AD7six** [comment]
i'm not saying that the current behavior is right - it isn't :)

However how does your change affect find list, find threaded and find neigbors, or find custom? it's still broken if 'only' find all is fixed and other broken use cases are still broken.

Edit: and it's not good that (as now) you can't detect the difference between no results and db error

**Comment by jameslarking** [comment]
oh ok sorry, misunderstood. good point about the other find options.  also good point about the difference between no results and db error - I think that will be a tricky one though since as the db is schemaless and if you do the following from the command line you don't get any errors:

```
 Jim$ mongo somedatabasethatdoesnotexist
MongoDB shell version: 1.6.3
connecting to: somedatabasethatdoesnotexist
> db.somecollectionthatdoesnotexist.find({})
> 
```

cheers

**Comment by AD7six** [comment]
ah - but that's not the sort of error I'm meaning, as it's not an error at all.

I am finding I often get mongo throwing exceptions (under load) in which case $result['ok'] is false. another easier example to test is with `$or => array('foo' => bar, 'zum' => zee)` (it's missing two arrays). Mongo will most definitely barf with that, and the result should be false, not an array. I might get to a more thorough look at things tomorrow.

**Pull request merged**
